### ISSUE TITLE
InvestigationReader fails to properly report missing sections at EOF

### ISSUE THREAD

**Issue by sellth** [bihealth/altamisa#104]
The ISA-tab i_file is pretty standardised in that all sections need to be included. Altamisa reports `ParseIsatabException` if during parsing an unexpected line is read i.e. a required section header is missing. If a section is missing at the end of the file however, an unrelated exception is thrown.

```py
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/sellts_c/Code/altamisa/altamisa/isatab/parse_investigation.py", line 163, in read
    studies = list(self._read_studies())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sellts_c/Code/altamisa/altamisa/isatab/parse_investigation.py", line 393, in _read_studies
    contacts = tuple(self._read_study_contacts())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sellts_c/Code/altamisa/altamisa/isatab/parse_investigation.py", line 584, in _read_study_contacts
    if not line[0] == investigation_headers.STUDY_CONTACTS:  # pragma: no cover
           ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

This is caused by Altamisa only checking for unexpected lines and not taking into account that missing sections at the end of file do not have any following lines.

**Comment by sellth** [comment]
fixed in #113
